### ISSUE TITLE
Tests pass, then fail

### ISSUE THREAD

**Issue by drewprice** [learn-co-curriculum/structured-learning#14]
The following tests both passed, and then failed without any changes being made. Other students had the same problem, and say that the remote build passed all the tests despite these two still failing locally.

* Bundler Gemfile groups should contain the pry gem in the development group using a hash argument to the gem method
```ruby
     Failure/Error: expect(bundle_output =~ /pry/).not_to eq(nil)
       
       expected: value != nil
            got: nil
       
       (compared using ==)
     # ./spec/bundler_spec.rb:51:in `block (4 levels) in <top (required)>'
```
 * Bundler Gemfile groups should contain the rspec gem in the test group using block syntax
```ruby     
      Failure/Error: expect(bundle_output =~ /rspec/).not_to eq(nil)
      
       expected: value != nil
            got: nil
       
       (compared using ==)
     # ./spec/bundler_spec.rb:68:in `block (4 levels) in <top (required)>'
```

**Comment by SophieDeBenedetto** [comment]
hi @drewprice, is this issue meant for this lab? there is no `bundler_spec` that I can see here.

**Comment by drewprice** [comment]
Hey @SophieDeBenedetto—my mistake! This issue should have been attached to the [using-bundler](https://github.com/learn-co-curriculum/using-bundler) lab, but in talking with @changamanda I think that it's been addressed now?

**Comment by AnnJohn** [comment]
Closing issue
