### ISSUE TITLE
environment.rb paragragh

### ISSUE THREAD

**Issue by garettarrowood** [learn-co-curriculum/structured-learning#3]
This paragraph is hard to read and understand.  Here is a possible edit (added a parathesis, split last sentence and fixed grammer):

Think of environment.rb as a manifest for all of your files. It should require all of your executable code (like what's in lib/). In turn, other code that executes it should require environment.rb.  It's easier and cleaner to require just this one file, then everything continuously updates whenever you add a new class.

**Comment by BenjaGross** [comment]
@garettarrowood Thanks for the suggestion, this is now in the read-me
